// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'rss_types.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'rss_types.g.dart';

@freezed
class RSSChannel with _$RSSChannel {
  const factory RSSChannel({
    required String title,
    required String link,
    required String description,
  }) = _RSSChannel;

  factory RSSChannel.fromJson(Map<String, Object?> json) =>
      _$RSSChannelFromJson(json);
}

@freezed
class RSSItem with _$RSSItem {
  const factory RSSItem({
    required RSSChannel channel,
    required String? title,
    required String? link,
    required String? description,
    required DateTime? pubDate,
  }) = _RSSItem;

  factory RSSItem.fromJson(Map<String, Object?> json) =>
      _$RSSItemFromJson(json);
}
